apiVersion: argoproj.io/v1alpha
kind: Application
metadata:
  name: argo-sample-application
  namespace: argocd
spec:
  projects: default
  source:
    repoURL: https://github.com/r0B-O/platform-dev.git
    targetRevision: feature/init
    path: apps/sample-01
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true  
