name: User Discovery CI

on: 
  workflow_dispatch:
  # push:
  #   branches:
  #     - '**'
  #     # - feature/init
  pull_request_target:
    types:
      - opened
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  # renovate: datasource=github-releases depName=GitTools/GitVersion registryUrl=https://github.com extractVersion=v
  GITVERSION_VERSION: '5.12.0'
  # renovate: datasource=github-releases depName=cli/cli registryUrl=https://github.com extractVersion=v
  GITHUB_CLI_VERSION: '2.28.0'
  CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY_HOST }}
  CONTAINER_REPOSITORY: ${{ github.repository }}
  GH_HOST: github.com
  GH_TOKEN: ${{ secrets.PA_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  getauthor:
    runs-on: self-hosted
    # needs:
    #   - gitversion
    steps:

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install gh cli
        uses: giantswarm/install-binary-action@v2.0.0
        with:
          binary: gh
          version: 2.47.0
          download_url: https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz
          tarball_binary_path: "*/bin/${binary}"
          smoke_test: ${binary} --version

      # This is needed to check out pull requests from a forked repository.
      # Branch name is following pattern: pull/${{ github.event.number }}/merge to simulate actions/checkout@v4 behaviour
      # in normal pull requests.
      - name: Check out code
        # if: ${{ contains(fromJSON('["pull_request_target", "pull_request"]'),github.event_name) }}
        run: |
          gh auth login --with-token $GH_TOKEN && gh config set prompt disabled && \
          gh pr checkout $PR_NUMBER -f -b pull/${{ github.event.number }}/merge
        env:
          GH_HOST: github.com
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Insert author name
        run: |
          ./update_author.sh
        env:
          GH_HOST: github.com
          GH_TOKEN: ${{ secrets.PA_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
